branch-defaults:
  master:
    environment: MovieApi-env
environment-defaults:
  MovieApi-env:
    branch: null
    repository: null
global:
  application_name: movie-api
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
